---
name: CI - Branches

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - dev
      - feat/*
      - fix/*
      - rel/*
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  secret:
    name: Call Secret Scanning
    uses: mighty-muffin/.github/.github/workflows/reusable-secret.yml@main
    secrets: inherit

  sca:
    name: Placeholder - Software Composition Analysis
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Run SCA
        run: echo Software Composition Analysis
        shell: bash

  sast:
    needs:
      - pre-commit
    name: Call Static Application Security Testing
    uses: mighty-muffin/.github/.github/workflows/reusable-sast.yml@main
    secrets: inherit

  unit-test:
    needs:
      - secret
      - sca
      - sast
    name: Run Unit Tests & Integration Tests
    uses: mighty-muffin/.github/.github/workflows/reusable-python-uv.yml@main

    with:
      working-directory: "fast-api"

  docker-build-push:
    needs:
      - unit-test
    name: Call Docker Build
    uses: mighty-muffin/.github/.github/workflows/reusable-docker-build.yml@main

    permissions:
      contents: read
      packages: write
      pull-requests: write

    with:
      file: "./docker/Dockerfile"
      push: false
