---
name: Continous Integration - Branches

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - dev
      - feat/*
      - fix/*
      - rel/*
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  secret:
    name: Call Secret Scanning
    uses: mighty-muffin/.github/.github/workflows/reusable-secret.yml@main
    secrets: inherit

  # sca:
  # sast:

  # unit-test:
  #   needs:
  #     - sast
  #     - secret
  #     - sca

  # docker-build-push:
  #   needs:
  #     - unit-test:
