---
name: Continous Integration - Branches

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - dev
      - feat/*
      - fix/*
      - rel/*
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  secret:
    name: Call Secret Scanning
    uses: mighty-muffin/.github/.github/workflows/reusable-secret.yml@main
    secrets: inherit

  sca:
    name: Placeholder - Software Composition Analysis
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Run SCA
        run: echo Software Composition Analysis
        shell: bash

  sast:
    name: Placeholder - Static Application Security Testing
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Run SAST
        run: echo Static Application Security Testing
        shell: bash

  unit-test:
    needs:
      - secret
      - sca
      - sast
    name: unit-test
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./fast-api

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

  # docker-build-push:
  #   needs:
  #     - unit-test:
