---
name: CI - PR

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  pre-commit:
    name: Call Pre-Commit run
    uses: mighty-muffin/.github/.github/workflows/reusable-pre-commit.yml@main

  secret:
    name: Call Secret Scanning
    uses: mighty-muffin/.github/.github/workflows/reusable-secret.yml@main
    secrets: inherit

  # sca:
  # sast:

  # unit-test:
  #   needs:
  #     - sast
  #     - secret
  #     - sca

  docker-build-push:
    needs:
      - pre-commit
      - secret
    name: Call Docker Build
    uses: mighty-muffin/.github/.github/workflows/reusable-docker-build.yml@main

    permissions:
      contents: read
      packages: write
      pull-requests: write

    with:
      file: "./docker/Dockerfile"
      platforms: |
          linux/amd64
          linux/arm64
