---
name: CI - PR

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  secret:
    name: Call Secret Scanning
    uses: mighty-muffin/.github/.github/workflows/reusable-secret.yml@main
    secrets: inherit

  pre-commit:
    name: Call Pre-Commit run
    uses: mighty-muffin/.github/.github/workflows/reusable-pre-commit.yml@main

  hello-world:
    needs:
      - pre-commit
      - secret
    name: Call Hello World
    uses: mighty-muffin/.github/.github/workflows/reusable-hello-world.yml@main
    with:
      comments: "Hello World from CI:pr"
      enable: false

  docker-build-push:
    name: Call Docker Build
    uses: mighty-muffin/.github/.github/workflows/reusable-docker-build.yml@main

    needs:
      - pre-commit
      - secret

    permissions:
      contents: read
      packages: write
      pull-requests: write

    with:
      file: "./docker/Dockerfile"
